module Jogos
  module TeamMapping
    WORLD_CUP_TEAM_SEARCH = {
      'Brasil' => 'Brazil',
      'Argentina' => 'Argentina',
      'França' => 'France',
      'Portugal' => 'Portugal',
      'Espanha' => 'Spain',
      'Inglaterra' => 'England',
      'Bélgica' => 'Belgium',
      'Alemanha' => 'Germany',
      'Holanda' => 'Netherlands',
      'Países Baixos' => 'Netherlands',
      'Croácia' => 'Croatia',
      'Suíça' => 'Switzerland',
      'Dinamarca' => 'Denmark',
      'Itália' => 'Italy',
      'Polônia' => 'Poland',
      'Sérvia' => 'Serbia',
      'Hungria' => 'Hungary',
      'Romênia' => 'Romania',
      'Áustria' => 'Austria',
      'Escócia' => 'Scotland',
      'País de Gales' => 'Wales',
      'Irlanda' => 'Republic of Ireland',
      'Irlanda do Norte' => 'Northern Ireland',
      'Turquia' => 'Turkey',
      'Rússia' => 'Russia',
      'Suécia' => 'Sweden',
      'Noruega' => 'Norway',
      'Finlândia' => 'Finland',
      'Bósnia e Herzegovina' => 'Bosnia and Herzegovina',
      'Eslováquia' => 'Slovakia',
      'Eslovênia' => 'Slovenia',
      'República Tcheca' => 'Czech Republic',
      'África do Sul' => 'South Africa',
      'Marrocos' => 'Morocco',
      'Tunísia' => 'Tunisia',
      'Argélia' => 'Algeria',
      'Camarões' => 'Cameroon',
      'Nigéria' => 'Nigeria',
      'Gana' => 'Ghana',
      'Senegal' => 'Senegal',
      'Costa do Marfim' => 'Ivory Coast',
      'Egito' => 'Egypt',
      'Mali' => 'Mali',
      'Togo' => 'Togo',
      'Kwait' => 'Kuwait',
      'Japão' => 'Japan',
      'Coreia do Sul' => 'South Korea',
      'Irã' => 'Iran',
      'Qatar' => 'Qatar',
      'Arábia Saudita' => 'Saudi Arabia',
      'Austrália' => 'Australia',
      'Nova Zelândia' => 'New Zealand',
      'Estados Unidos' => 'United States',
      'EUA' => 'United States',
      'Estados Unidos da América' => 'United States',
      'Canadá' => 'Canada',
      'México' => 'Mexico',
      'Panamá' => 'Panama',
      'Costa Rica' => 'Costa Rica',
      'Honduras' => 'Honduras',
      'Colômbia' => 'Colombia',
      'Peru' => 'Peru',
      'Chile' => 'Chile',
      'Uruguai' => 'Uruguay',
      'Equador' => 'Ecuador',
      'Bolívia' => 'Bolivia',
      'Paraguai' => 'Paraguay',
      'Venezuela' => 'Venezuela'
    }.freeze

    def self.api_search_name(local_name)
      return nil if local_name.blank?

      normalized = local_name.strip
      WORLD_CUP_TEAM_SEARCH.fetch(normalized, normalized)
    end
  end
end
