name: Deploy para DigitalOcean

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Executar deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /orangScore

            APP_DIR="/home/deploy/orangScore"

            cd $APP_DIR
            git pull origin master

            set -a
            source /etc/orangscore.env
            set +a

            bundle config set without 'development test'
            bundle install

            yarn install

            RAILS_ENV=production rails tmp:clear
            RAILS_ENV=production rails log:clear

            RAILS_ENV=production rails db:migrate

            RAILS_ENV=production rails assets:precompile

            sudo systemctl restart orangscore